asocial/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("asome.urls"))
]

asome/urls.py
from django.urls import path
from . import views

app_name = "asome"

urlpatterns = [
    path("", views.index, name="index"),
    path("t", views.add_topic, name="add_topic"),
    path("t/<str:topic_name>", views.topic, name="topic"),
    path("t/<str:topic_name>/like", views.like_topic, name="like_topic"),
    path("t/<str:topic_name>/dislike", views.dislike_topic, name="dislike_topic"),
    path("t/<str:topic_name>/comment", views.post_comment, name="post_comment"),
    path("u/<str:username>", views.user, name="user"),
    path("register", views.register, name="register"),
]

asome/models.py
from django.db import models


class Topic(models.Model):
    name = models.CharField(max_length=97, unique=True)
    date = models.DateTimeField("date created", auto_now_add=True)

    def __str__(self):
        return self.name


class User(models.Model):
    name = models.CharField(max_length=29, unique=True)
    secret = models.UUIDField()
    date = models.DateTimeField("date joined", auto_now_add=True)
    verified = models.BooleanField(default=False)
    likes = models.ManyToManyField(to=Topic, related_name="likes", blank=True)
    dislikes = models.ManyToManyField(to=Topic, related_name="dislikes", blank=True)

    def __str__(self):
        return self.name


class Comment(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, related_name="comments")
    submitter = models.ForeignKey(User, on_delete=models.CASCADE, related_name="comments")
    date = models.DateTimeField("date submitted", auto_now_add=True)
    content = models.CharField(max_length=1024)

    def __str__(self):
        return f"Comment by {self.submitter} on {self.topic.name}"

asome/forms.py
import uuid
from django import forms


class UserForm(forms.Form):
    username = forms.CharField(label="Username", min_length=3, max_length=29)
    secret = forms.UUIDField(initial=uuid.uuid4, widget=forms.HiddenInput())


class TopicForm(forms.Form):
    name = forms.CharField(label="Suggest a new topic", max_length=97)

asome/views.py
from typing import Optional
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse

from asome.models import Topic, User, Comment
from asome.forms import UserForm, TopicForm


def index(request):
    ctx = {
        "topics": Topic.objects.all(),
        "recently_joined_users": User.objects.order_by("-date")[:5],
        "topic_form": TopicForm()
    }
    return render(request, "asome/index.html", ctx)


def topic(request, topic_name):
    topic = get_object_or_404(Topic, name=topic_name)
    ctx = {
        "topic": topic,
    }
    return render(request, "asome/topic.html", ctx)


def like_topic(request, topic_name):
    liked_topic = get_object_or_404(Topic, name=topic_name)
    user = valid_user(request)
    if user is None:
        return HttpResponse("Invalid user credentials", status=401)
    if user.likes.filter(pk=liked_topic.id).exists():
        user.likes.remove(liked_topic)
    else:
        user.likes.add(liked_topic)
    return topic(request, topic_name)


def dislike_topic(request, topic_name):
    disliked_topic = get_object_or_404(Topic, name=topic_name)
    user = valid_user(request)
    if user is None:
        return HttpResponse("Invalid user credentials", status=401)
    if user.dislikes.filter(pk=disliked_topic.id).exists():
        user.dislikes.remove(disliked_topic)
    else:
        user.dislikes.add(disliked_topic)
    return topic(request, topic_name)


def user(request, username):
    user = get_object_or_404(User, name=username)
    ctx = {
        "user": user,
    }
    return render(request, "asome/user.html", ctx)


def register(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            username = data["username"]
            secret = data["secret"]
            if User.objects.filter(name=username).exists():
                return HttpResponse("an user with that username already exists")
            new_user = User(name=username, secret=secret)
            new_user.save()
            ctx = {
                "user": new_user
            }
            return render(request, "asome/welcome.html", ctx)
        else:
            return HttpResponse("registration unsuccessful")
    ctx = {
        "form": UserForm()
    }
    return render(request, "asome/register.html", ctx)


def post_comment(request, topic_name):
    commented_topic = get_object_or_404(Topic, name=topic_name)
    user = valid_user(request)
    if user is None:
        return HttpResponse("Invalid user credentials", status=401)
    comment = Comment(topic=commented_topic, submitter=user, content=request.POST["content"])
    comment.save()
    return topic(request, topic_name)


def add_topic(request):
    if request.method != "POST":
        return HttpResponse("unsupported method (this end point only supports POST)")
    form = TopicForm(request.POST)
    if not form.is_valid():
        return HttpResponse("unlucky")
    topic_name = form.cleaned_data["name"]
    new_topic = Topic(name=topic_name)
    new_topic.save()
    return topic(request, topic_name)


def valid_user(request) -> Optional[User]:
    form = UserForm(request.POST)
    if not form.is_valid():
        return None
    data = form.cleaned_data
    username = data["username"]
    secret = data["secret"]
    try:
        return User.objects.get(name=username, secret=secret)
    except User.DoesNotExist:
        return None

asome/templates/asome/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>asome</title>
</head>
<body>
<header>
    <a href={% url 'asome:index' %} class="header-link">Home</a>
    <a href={% url 'asome:register' %} class="header-link">Register</a>
</header>
{% block content %}
{% endblock %}
<script>
function onFormData(event) {
    const username = window.localStorage.getItem("username")
    const secret = window.localStorage.getItem("secret")
    if (username && secret) {
        event.formData.append("username", username)
        event.formData.append("secret", secret)
    }
}
for (let uform of document.getElementsByClassName("uform")) {
    uform.addEventListener("formdata", onFormData)
}
</script>
</body>
</html>

asome/templates/asome/comment.html
{% load custom_tags %}

<div class="comment">
    <div class="comment-submitter">
        {% user_link comment.submitter %}
    </div>
    <div class="comment-timestamp" title="{{ comment.date|date:'r' }}">
        {{ comment.date | date }}
    </div>
    <div class="comment-content">
        {{ comment.content }}
    </div>
</div>

asome/templates/asome/index.html
{% extends 'asome/base.html' %}
{% load custom_tags %}

{% block content %}
<h2>What is this?</h2>
<ul>
<li>There are no friendships. Treat everyone as you would your worst enemy.</li>
<li>The concept revolves around <i>topics</i>, which you may comment on and like/dislike.</li>
<li>You can't vote on comments, every comment is equal.</li>
<li>To create an "account" you only need to provide a username. We don't want to store your email address (or any other personal data).</li>
<li>There are no rules, but the admins are tyrants.</li>
</ul>

<h2>Topics</h2>
<div class="front-page-topics">
{% for topic in topics %}
    {% topic_link topic %}
{% endfor %}
<form method="POST" action={% url 'asome:add_topic' %}>
    {% csrf_token %}
    {{ topic_form }}
</form>
</div>


<h2>Recently joined</h2>
<div class="recently-joined">
    {% for user in recently_joined_users %}
        {% user_link user %}
    {% endfor %}
</div>
{% endblock %}

asome/templates/asome/register.html
{% extends 'asome/base.html' %}

{% block content %}
<h2>Create a new user</h2>
<form action="/register" method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Register</button>
</form>
{% endblock %}

asome/templates/asome/topic.html
{% extends 'asome/base.html' %}
{% load custom_tags %}

{% block content %}
<h2>{{ topic.name }}</h2>
<span class="topic-likes">{{ topic.likes.all|length }}</span>
<span class="topic-dislikes">{{ topic.dislikes.all|length }}</span>
<span>Topic created on {{ topic.date|date:"F jS Y" }}</span>

<form class="uform" method="POST" action={% url 'asome:like_topic' topic.name %}>
    {% csrf_token %}
    <button type="submit">Like</button>
</form>
<form class="uform" method="POST" action={% url 'asome:dislike_topic' topic.name %}>
    {% csrf_token %}
    <button type="submit">
        Dislike
    </button>
</form>

<h3>Comments</h3>
{% for comment in topic.comments.all %}
{% show_comment comment %}
{% empty %}
<p>No one cares about this topic enough to have commented on it!</p>
{% endfor %}

<form class="uform" method="POST" action={% url 'asome:post_comment' topic.name %}>
    {% csrf_token %}
    <label for="content">Leave a comment</label>
    <div class="comment-textarea-container">
    <textarea id="content" name="content" type="text"></textarea>
    </div>
    <button type="submit">Send</button>
</form>

{% endblock %}

asome/templates/asome/topic_link.html
<a href={% url 'asome:topic' topic.name %} class="topic-link">{{topic.name}}</a>

asome/templates/asome/user.html
{% extends 'asome/base.html' %}
{% load custom_tags %}

{% block content %}
<h2 class="user-title">{{ user.name }}</h2>

<h3>Likes</h3>
{% for like in user.likes.all %}
<div class="like">
    {% topic_link like %}
</div>
{% empty %}
<p>
    {{ user.name }} does not like anything
</p>
{% endfor %}

<h3>Dislikes</h3>
{% for dislike in user.dislikes.all %}
<div class="dislike">
    {% topic_link dislike %}
</div>
{% empty %}
<p>
    {{ user.name }} has no dislikes yet
</p>
{% endfor %}
{% endblock %}

asome/templates/asome/user_link.html
<div class="user-link">
    <a href={% url 'asome:user' user.name %}>{{ user.name }}</a>
    (<span title="likes">{{ user.likes.all|length }}</span> -
    <span title="dislikes">{{ user.dislikes.all|length }}</span> -
    <span title="comments">{{ user.comments.all|length }}</span>)
</div>

asome/templates/asome/welcome.html
{% extends 'asome/base.html' %}

{% block content %}
<p>Welcome to asome, {{ user.name }}</p>
<p>Your username shall be accessible with this secret code: {{ user.secret }}</p>
<p>
    note that this is not meant to be super secure, there are probably ways to hijack your username (and we encourage you to try too, hijacking accounts is commendable antisocial behaviour)
</p>
<script>
    window.localStorage.setItem("username", "{{ user.name }}")
    window.localStorage.setItem("secret", "{{ user.secret }}")
</script>
{% endblock %}